#!/usr/bin/python3

def call_error(test, info):
    assert not test, "(caught) %s" % info

